#config .yaml to compute features for Training from audio and annotations
paths:
 scratch_raw: "path_to_your_audio"
 features_dir: "output_path_to_your_tensors"
 train_json: "my_path/Train_data.json"
 eval_json: "my_path/Validation_data.json"
 test_json: "my_path/Test_data.json"

whisper:
 model: "large"
 language: "French"
 task: "transcribe"

preprocessing:
 target_sr: 16000

